# Check out https://docs.codemagic.io/yaml/building-a-react-native-app/ for more information
# Please review and update values

workflows:
  react-native-android-beta-app-center:
    name: React Native Android Beta App Center
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - staging
      node: v18.17.1
    scripts:
      - npm install
      - npm test
      - bundle install
      - bundle exec fastlane android beta
    triggering:
      events: # List the events that trigger builds
        - push
      branch_patterns: # Include or exclude watched branches
        - pattern: 'main'
          include: true
          source: true
